### ISSUE TITLE
Consider checking profiles for names

### ISSUE THREAD

**Issue by sharwell** [dotnet/org-policies#4]
This is a proposed rule for members in the Microsoft group: users should have their first and last name set as part of their GitHub profile. This helps with team maintenance, searches, and transparency in open source.

**Comment by terrajobst** [comment]
Tagging @dotnet/policy-cops.

I can see why this would be useful. At the same time, I've heard concerns from people that they don't want their full names displayed on the internet. They are arguing that their full name is very unique and can identify them in real life too. As a person with a unique first & last name combination, I can relate. I have given up on that a long time ago and my Twitter/YouTube presence is very hard to eradicate. But this was a choice I a made. I don't think it's reasonable for us to force that all 1,200 folks in the Microsoft team. FWIW, we have the linking information to their Microsoft account. And if you are an employee, you can install the Chrome extension that modifies the HTML to show that information when you browse GitHub.

@jaredpar @richlander what are your thoughts?

**Comment by jaredpar** [comment]
I've heard the same concerns about making it easier to identify people in real life.

I also don't think it's necessary to have real identities attached to our contributions. Consider that no one is suggesting a similar rule for non-MSFT contributors. Probably because it would turn off many contributors who value keeping their true identity private.

There are several contributors to .NET today who I know don't use their real names. Specifically because they value having an online identity separate of that from their real one. Why should Microsoft employees be held to a different standard here?

**Comment by sharwell** [comment]
I would be comfortable with allowing a "policy exception" label be applied if the user does not wish to make this change (no reason necessary for the exception to be granted). I'm more interested in cases where the user does not realize that their name is not set.

**Comment by HollyAM** [comment]
I have similarly struggled to associate github identities to Microsoft email aliases and I think it is important for employees to be able to easily discover those associations. However, it is also important for there to be a way for employees to create aliases in order to feel and be safer. Specifically, anyone who knows my full name knows my home address, because of that I limit my online interactions to try not to attract negative attention. Unless Microsoft is offering a personal security detail for me and my family, they should allow me some level of anonymity to feel safe.

**Comment by terrajobst** [comment]
Thanks @HollyAM.

Based on your comment and what @jaredpar and I've heard from others we want pursue such a policy.
